In [1]:
import pandas as pd
import numpy as np
from copy import deepcopy

In [2]:
pd.set_option('display.float_format', lambda x: '%.2f' % x)
pd.set_option('display.max_columns', None)

In [3]:
df = pd.read_csv('../Data Sources/gun_violence_archive_scraped.csv')

df.loc[df['n_guns_involved'].astype(str) == 'nan', 'n_guns_involved'] = None
df.loc[df['state_senate_district'].astype(str) == 'nan', 'state_senate_district'] = None
df.loc[df['congressional_district'].astype(str) == 'nan', 'congressional_district'] = None
df.loc[df['location_description'].astype(str) == 'None', 'location_description'] = None
df.loc[df['state_house_district'].astype(str) == 'nan', 'state_house_district'] = None
df.loc[df['state_senate_district'].astype(str) == 'nan', 'state_senate_district'] = None

df['date'] = pd.to_datetime(df['date'])
df['incident_id'] = df['incident_id'].astype(int)
df['n_guns_involved'] = df['n_guns_involved'].astype(float)
df['state_senate_district'] = df['state_senate_district'].astype(float)
df['location_description'] = df['location_description'].astype(str)
df['congressional_district'] = df['congressional_district'].astype(float)
df['state_senate_district'] = df['state_senate_district'].astype(float)
df['gun_stolen'] = df['gun_stolen'].astype(str)
df['incident_characteristics'] = df['incident_characteristics'].astype(str)
df['participant_relationship'] = df['participant_relationship'].astype(str)

df.loc[(['Stolen' in s for s in df['gun_stolen']]), 'gun_stolen'] = "1"
df.loc[(['stolen' in s for s in df['gun_stolen']]), 'gun_stolen'] = "1"
df.loc[(['Gun(s) stolen' in s for s in df['incident_characteristics']]), 'gun_stolen'] = "1"
df.loc[(['Stolen/Illegally owned gun{s}' in s for s in df['incident_characteristics']]), 'gun_stolen'] = "1"
df.loc[(['stolen gun' in s for s in df['incident_characteristics']]), 'gun_stolen'] = "1"
df.loc[df['gun_stolen']!="1", 'gun_stolen'] = "0"
df.loc[(['Suicide' in s for s in df['incident_characteristics']]), 'suicide'] = "1"
df.loc[(['suicide' in s for s in df['incident_characteristics']]), 'suicide'] = "1"
df.loc[df['suicide']!="1", 'suicide'] = "0"
df.loc[(['Accidental' in s for s in df['incident_characteristics']]), 'accidental'] = "1"
df.loc[(['accidental' in s for s in df['incident_characteristics']]), 'accidental'] = "1"
df.loc[df['accidental']!="1", 'accidental'] = "0"
df.loc[(['Domestic Violence' in s for s in df['incident_characteristics']]), 'domestic_violence'] = "1"
df.loc[(['Domestic Violence' not in s for s in df['incident_characteristics']]), 'domestic_violence'] = "0"
df.loc[(['Gang' in s for s in df['participant_relationship']]), 'gang_related'] = "1"
df.loc[(['Gang' in s for s in df['incident_characteristics']]), 'gang_related'] = "1"
df.loc[df['gang_related']!="1", 'gang_related'] = "0"
df.loc[(['Non-Shooting Incident' in s for s in df['incident_characteristics']]), 'non_shooting_incident'] = "1"
df.loc[df['non_shooting_incident']!="1", 'non_shooting_incident'] = "0"
df.loc[(['Gun shop robbery' in s for s in df['incident_characteristics']]), 'gun_shop_robbery'] = "1"
df.loc[df['gun_shop_robbery']!="1", 'gun_shop_robbery'] = "0"
df.loc[(['Drive-by' in s for s in df['incident_characteristics']]), 'drive_by_shooting'] = "1"
df.loc[df['drive_by_shooting']!="1", 'drive_by_shooting'] = "0"
df.loc[(['Officer Involved Shooting' in s for s in df['incident_characteristics']]), 'officer_involved_shooting'] = "1"
df.loc[df['officer_involved_shooting']!="1", 'officer_involved_shooting'] = "0"
df.loc[(['Child' in s for s in df['incident_characteristics']]), 'child_involved'] = "1"
df.loc[df['child_involved']!="1", 'child_involved'] = "0"
df.loc[(['Mass Shooting' in s for s in df['incident_characteristics']]), 'mass_shooting'] = "1"
df.loc[df['mass_shooting']!="1", 'mass_shooting'] = "0"
df.loc[(['Drug' in s for s in df['incident_characteristics']]), 'drug_involved'] = "1"
df.loc[df['drug_involved']!="1", 'drug_involved'] = "0"
df.loc[(['Assault weapon' in s for s in df['incident_characteristics']]), 'assault_weapon'] = "1"
df.loc[df['assault_weapon']!="1", 'assault_weapon'] = "0"

df['gun_stolen'] = df['gun_stolen'].astype(int)
df['suicide'] = df['suicide'].astype(int)
df['accidental'] = df['accidental'].astype(int)
df['domestic_violence'] = df['domestic_violence'].astype(int)
df['gang_related'] = df['gang_related'].astype(int)
df['non_shooting_incident'] = df['non_shooting_incident'].astype(int)
df['gun_shop_robbery'] = df['gun_shop_robbery'].astype(int)
df['drive_by_shooting'] = df['drive_by_shooting'].astype(int)
df['officer_involved_shooting'] = df['officer_involved_shooting'].astype(int)
df['child_involved'] = df['child_involved'].astype(int)
df['mass_shooting'] = df['mass_shooting'].astype(int)
df['drug_involved'] = df['drug_involved'].astype(int)
df['assault_weapon'] = df['assault_weapon'].astype(int)

df['participant_type'] = df['participant_type'].replace('\|', ':', regex = True).str.split(":")
df['participant_status'] = df['participant_status'].replace('\|', ':', regex = True).str.split(":")
df['participant_gender'] = df['participant_gender'].replace('\|', ':', regex = True).str.split(":")
df['participant_age'] = df['participant_age'].replace('\|', ':', regex = True).str.split(":")

df.rename({'n_killed': 'num_killed', 'n_injured': 'num_injured',
           'n_guns_involved': 'num_guns_involved'}, axis = 1, inplace = True)

In [4]:
df.drop(['address', 'incident_url', 'source_url',
         'incident_url_fields_missing', 'sources',
         'incident_characteristics', 'participant_name',
         'participant_gender', 'participant_relationship',
         'gun_type', 'participant_age_group',
         'location_description', 'notes'], axis = 1, inplace = True)

In [5]:
print(len(df[df['participant_type'].isnull()==False]['participant_type']))
print(len(df[df['participant_status'].isnull()==False]['participant_status']))
print(len(df[df['participant_age'].isnull()==False]['participant_age']))

214814
212051
147379

In [6]:
print('gun_stolen', len(df[df['gun_stolen']==1]))
print('suicide', len(df[df['suicide']==1]))
print('accidental', len(df[df['accidental']==1]))
print('domestic_violence', len(df[df['domestic_violence']==1]))
print('gang_related', len(df[df['gang_related']==1]))
print('non_shooting_incident', len(df[df['non_shooting_incident']==1]))
print('gun_shop_robbery', len(df[df['gun_shop_robbery']==1]))
print('drive_by_shooting', len(df[df['drive_by_shooting']==1]))
print('officer_involved_shooting', len(df[df['officer_involved_shooting']==1]))
print('child_involved', len(df[df['child_involved']==1]))
print('mass_shooting', len(df[df['mass_shooting']==1]))
print('drug_involved', len(df[df['drug_involved']==1]))
print('assault_weapon', len(df[df['assault_weapon']==1]))

gun_stolen 15404
suicide 55505
accidental 59855
domestic_violence 10841
gang_related 5690
non_shooting_incident 44837
gun_shop_robbery 597
drive_by_shooting 13655
officer_involved_shooting 14050
child_involved 2123
mass_shooting 1637
drug_involved 17099
assault_weapon 2052

In [7]:
df.to_pickle('../Pickles/df1.pkl')

In [8]:
df = pd.read_pickle('../Pickles/df1.pkl')

In [9]:
df.head()

,incident_id,date,state,city_or_county,num_killed,num_injured,congressional_district,gun_stolen,latitude,longitude,num_guns_involved,participant_age,participant_status,participant_type,state_house_district,state_senate_district,suicide,accidental,domestic_violence,gang_related,non_shooting_incident,gun_shop_robbery,drive_by_shooting,officer_involved_shooting,child_involved,mass_shooting,drug_involved,assault_weapon
0,461105,2013-01-01,Pennsylvania,Mckeesport,0,4,14.00,0,40.35,-79.86,nan,"[0, , 20]","[0, , Arrested, , 1, , Injured, , 2, , Injured...","[0, , Victim, , 1, , Victim, , 2, , Victim, , ...",nan,nan,0,0,0,0,0,0,0,0,0,1,0,0
1,460726,2013-01-01,California,Hawthorne,1,3,43.00,0,33.91,-118.33,nan,"[0, , 20]","[0, , Killed, , 1, , Injured, , 2, , Injured, ...","[0, , Victim, , 1, , Victim, , 2, , Victim, , ...",62.00,35.00,1,1,0,1,0,0,0,0,0,1,0,0
2,478855,2013-01-01,Ohio,Lorain,1,3,9.00,0,41.45,-82.14,2.00,"[0, , 25, , 1, , 31, , 2, , 33, , 3, , 34, , 4...","[0, , Injured, Unharmed, Arrested, , 1, , Unha...","[0, , Subject-Suspect, , 1, , Subject-Suspect,...",56.00,13.00,1,1,0,0,0,0,0,0,0,0,0,0
3,478925,2013-01-05,Colorado,Aurora,4,0,6.00,0,39.65,-104.80,nan,"[0, , 29, , 1, , 33, , 2, , 56, , 3, , 33]","[0, , Killed, , 1, , Killed, , 2, , Killed, , ...","[0, , Victim, , 1, , Victim, , 2, , Victim, , ...",40.00,28.00,1,1,0,0,0,0,0,1,0,0,1,0
4,478959,2013-01-07,North Carolina,Greensboro,2,2,6.00,0,36.11,-79.96,2.00,"[0, , 18, , 1, , 46, , 2, , 14, , 3, , 47]","[0, , Injured, , 1, , Injured, , 2, , Killed, ...","[0, , Victim, , 1, , Victim, , 2, , Victim, , ...",62.00,27.00,1,1,1,0,0,0,0,0,0,0,0,0

In [10]:
df.columns

Index(['incident_id', 'date', 'state', 'city_or_county', 'num_killed',
       'num_injured', 'congressional_district', 'gun_stolen', 'latitude',
       'longitude', 'num_guns_involved', 'participant_age',
       'participant_status', 'participant_type', 'state_house_district',
       'state_senate_district', 'suicide', 'accidental', 'domestic_violence',
       'gang_related', 'non_shooting_incident', 'gun_shop_robbery',
       'drive_by_shooting', 'officer_involved_shooting', 'child_involved',
       'mass_shooting', 'drug_involved', 'assault_weapon'],
      dtype='object')

In [11]:
part_type_df = df.set_index(['incident_id'])['participant_type'].apply(pd.Series).stack().reset_index(level=1, drop=True)
part_type_df = part_type_df.reset_index()
part_type_df.columns = ['incident_id','participant_type']
part_type_df = part_type_df[(part_type_df['participant_type']=='Victim') | (part_type_df['participant_type']=='Subject-Suspect')]
part_type_df['participant_index'] = part_type_df.groupby('incident_id').cumcount()
part_type_df = part_type_df.reset_index()
part_type_df.drop(['index'], axis = 1, inplace = True)

part_age_df = df.set_index(['incident_id'])['participant_age'].apply(pd.Series).stack().reset_index(level=1, drop=True)
part_age_df = part_age_df.reset_index()
part_age_df.columns = ['incident_id','participant_age']
part_age_df = part_age_df[part_age_df['participant_age'] != '']
part_age_df = pd.DataFrame({'incident_id': part_age_df['incident_id'].iloc[::2].values, 'participant_index': part_age_df['participant_age'].iloc[::2].values, 'participant_age': part_age_df['participant_age'].iloc[1::2].values})
part_age_df['participant_index'] = part_age_df['participant_index'].astype(int)

part_status_df = df.set_index(['incident_id'])['participant_status'].apply(pd.Series).stack().reset_index(level=1, drop=True)
part_status_df = part_status_df.reset_index()
part_status_df.columns = ['incident_id','participant_status']
part_status_df = part_status_df[part_status_df['participant_status'] != '']
part_status_df = pd.DataFrame({'incident_id': part_status_df['incident_id'].iloc[::2].values, 'participant_index': part_status_df['participant_status'].iloc[::2].values, 'participant_status': part_status_df['participant_status'].iloc[1::2].values})
part_status_df['participant_index'] = part_status_df['participant_index'].astype(int)

In [15]:
part_df = pd.merge(part_type_df, part_age_df, on=['incident_id', 'participant_index'], how='outer')
part_df = pd.merge(part_df, part_status_df, on=['incident_id', 'participant_index'], how='outer')

part_df['participant_type'] = part_df['participant_type'].astype(str)
part_df['participant_status'] = part_df['participant_status'].astype(str)
part_df['participant_age'] = part_df['participant_age'].astype(float)

part_df.loc[(['Unharmed' in s for s in part_df['participant_status']]), 'num_unharmed'] = 1
part_df.loc[(['Unharmed' not in s for s in part_df['participant_status']]), 'num_unharmed'] = 0
part_df.loc[(['Arrested' in s for s in part_df['participant_status']]), 'num_arrested'] = 1
part_df.loc[(['Arrested' not in s for s in part_df['participant_status']]), 'num_arrested'] = 0

# part_df.loc[(['Killed' in s for s in part_df['participant_status']]), 'num_killed_check'] = 1
# part_df.loc[(['Killed' not in s for s in part_df['participant_status']]), 'num_killed_check'] = 0
# part_df.loc[(['Injured' in s for s in part_df['participant_status']]), 'num_injured_check'] = 1
# part_df.loc[(['Injured' not in s for s in part_df['participant_status']]), 'num_injured_check'] = 0

In [16]:
part_df.head()

,incident_id,participant_type,participant_index,participant_age,participant_status,num_unharmed,num_arrested
0,461105,Victim,0,20.00,Arrested,0.00,1.00
1,461105,Victim,1,nan,Injured,0.00,0.00
2,461105,Victim,2,nan,Injured,0.00,0.00
3,461105,Victim,3,nan,Injured,0.00,0.00
4,461105,Subject-Suspect,4,nan,Injured,0.00,0.00

In [17]:
aggregations_1 = {
    'num_unharmed': 'sum',
    'num_arrested': 'sum',
#     'num_killed_check': 'sum',
#     'num_injured_check': 'sum',
    }

aggregations_2 = {
    'participant_index': 'count',
    'participant_age': 'mean',
    }

part_status_df_group = part_df.groupby(['incident_id']).agg(aggregations_1).reset_index()
part_df_group = part_df.groupby(['incident_id']).agg(aggregations_2).reset_index()
part_type_df_group = part_df.groupby(['incident_id', 'participant_type']).agg(aggregations_2).reset_index()
victim_df = deepcopy(part_type_df_group[part_type_df_group['participant_type']=='Victim'])
suspect_df = deepcopy(part_type_df_group[part_type_df_group['participant_type']=='Subject-Suspect'])

part_df_group['participant_age_ratio'] = part_df_group['participant_index']/part_df_group['participant_age']
victim_df['victim_age_ratio'] = victim_df['participant_index']/victim_df['participant_age']
suspect_df['suspect_age_ratio'] = suspect_df['participant_index']/suspect_df['participant_age']

part_df_group.rename({'participant_age': 'avg_participant_age', 'participant_index': 'num_participants'}, axis = 1, inplace = True)
victim_df.rename({'participant_age': 'avg_victim_age', 'participant_index': 'num_victims'}, axis = 1, inplace = True)
suspect_df.rename({'participant_age': 'avg_suspect_age', 'participant_index': 'num_suspects'}, axis = 1, inplace = True)

victim_df.drop(['participant_type'], axis = 1, inplace = True)
suspect_df.drop(['participant_type'], axis = 1, inplace = True)

In [21]:
len(df)

239677

In [22]:
df = pd.merge(df, part_df_group, on=['incident_id'], how='outer')
df = pd.merge(df, part_status_df_group, on=['incident_id'], how='outer')
df = pd.merge(df, victim_df, on=['incident_id'], how='outer')
df = pd.merge(df, suspect_df, on=['incident_id'], how='outer')

df.loc[df['num_suspects'].isnull(), 'num_suspects'] = 0
df.drop(['participant_age', 'participant_status', 'participant_type'], axis = 1, inplace = True)

In [24]:
# id for las vegas shooting chosing arbitrarily
# added las vegas shooting (originally missing from dataset)
df_append_1 = pd.DataFrame(np.array([
    100117, '2017-10-01', 'Nevada', 'Las Vegas', 59,
    489, None, 0, 36.08833298, -115.171499314, 47,
    None, None, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1,
    910, 35.23232323, 0.028383028, 851, 0, 195,
    34.93877551, 5.581191589, 1, 64, 0.015625]).reshape(1, -1),
                           columns = list(df.columns))
# added incident 1081885 (originally missing from dataset)
df_append_2 = pd.DataFrame(np.array([
    1081885, '2018-02-18', 'Arkansas', 'Hermitage',
    1, 0, 4, 0, 33.393644, -92.224399, 1,
    8, 26, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    2, 48, 0.04166666666, 1, 1, 1,
    38, 0.02631578947, 1, 58, 0.01724137931]).reshape(1, -1),
                         columns = list(df.columns))
df = df.append([df_append_1, df_append_2], ignore_index = True)

df['date'] = pd.to_datetime(df['date'])
df['incident_id'] = df['incident_id'].astype(int)
df['latitude'] = df['latitude'].astype(float)
df['longitude'] = df['longitude'].astype(float)
df['num_guns_involved'] = df['num_guns_involved'].astype(float)
df['congressional_district'] = df['congressional_district'].astype(float)
df['state_house_district'] = df['state_house_district'].astype(float)
df['state_senate_district'] = df['state_senate_district'].astype(float)
df['num_killed'] = df['num_killed'].astype(int)
df['num_injured'] = df['num_injured'].astype(int)
df['gun_stolen'] = df['gun_stolen'].astype(int)
df['suicide'] = df['suicide'].astype(int)
df['accidental'] = df['accidental'].astype(int)
df['domestic_violence'] = df['domestic_violence'].astype(int)
df['gang_related'] = df['gang_related'].astype(int)
df['non_shooting_incident'] = df['non_shooting_incident'].astype(int)
df['gun_shop_robbery'] = df['gun_shop_robbery'].astype(int)
df['drive_by_shooting'] = df['drive_by_shooting'].astype(int)
df['officer_involved_shooting'] = df['officer_involved_shooting'].astype(int)
df['child_involved'] = df['child_involved'].astype(int)
df['mass_shooting'] = df['mass_shooting'].astype(int)
df['drug_involved'] = df['drug_involved'].astype(int)
df['assault_weapon'] = df['assault_weapon'].astype(int)
df['avg_participant_age'] = df['avg_participant_age'].astype(float)
df['participant_age_ratio'] = df['participant_age_ratio'].astype(float)
df['num_unharmed'] = df['num_unharmed'].astype(float)
df['num_arrested'] = df['num_arrested'].astype(float)
df['num_victims'] = df['num_victims'].astype(float)
df['avg_victim_age'] = df['avg_victim_age'].astype(float)
df['victim_age_ratio'] = df['victim_age_ratio'].astype(float)
df['num_suspects'] = df['num_suspects'].astype(int)
df['avg_suspect_age'] = df['avg_suspect_age'].astype(float)
df['suspect_age_ratio'] = df['suspect_age_ratio'].astype(float)
df['num_participants'] = df['num_participants'].astype(float)

In [25]:
len(df)

239679

In [26]:
df.to_pickle('../Pickles/df2.pkl')

In [27]:
df = pd.read_pickle('../Pickles/df2.pkl')

In [28]:
df.head()

,incident_id,date,state,city_or_county,num_killed,num_injured,congressional_district,gun_stolen,latitude,longitude,num_guns_involved,state_house_district,state_senate_district,suicide,accidental,domestic_violence,gang_related,non_shooting_incident,gun_shop_robbery,drive_by_shooting,officer_involved_shooting,child_involved,mass_shooting,drug_involved,assault_weapon,num_participants,avg_participant_age,participant_age_ratio,num_unharmed,num_arrested,num_victims,avg_victim_age,victim_age_ratio,num_suspects,avg_suspect_age,suspect_age_ratio
0,461105,2013-01-01,Pennsylvania,Mckeesport,0,4,14.00,0,40.35,-79.86,nan,nan,nan,0,0,0,0,0,0,0,0,0,1,0,0,5.00,20.00,0.25,0.00,1.00,4.00,20.00,0.20,1,nan,nan
1,460726,2013-01-01,California,Hawthorne,1,3,43.00,0,33.91,-118.33,nan,62.00,35.00,1,1,0,1,0,0,0,0,0,1,0,0,5.00,20.00,0.25,0.00,0.00,4.00,20.00,0.20,1,nan,nan
2,478855,2013-01-01,Ohio,Lorain,1,3,9.00,0,41.45,-82.14,2.00,56.00,13.00,1,1,0,0,0,0,0,0,0,0,0,0,5.00,31.20,0.16,2.00,2.00,3.00,33.33,0.09,2,28.00,0.07
3,478925,2013-01-05,Colorado,Aurora,4,0,6.00,0,39.65,-104.80,nan,40.00,28.00,1,1,0,0,0,0,0,1,0,0,1,0,4.00,37.75,0.11,0.00,0.00,3.00,39.33,0.08,1,33.00,0.03
4,478959,2013-01-07,North Carolina,Greensboro,2,2,6.00,0,36.11,-79.96,2.00,62.00,27.00,1,1,1,0,0,0,0,0,0,0,0,0,4.00,31.25,0.13,0.00,0.00,3.00,26.00,0.12,1,47.00,0.02

In [29]:
df.columns

Index(['incident_id', 'date', 'state', 'city_or_county', 'num_killed',
       'num_injured', 'congressional_district', 'gun_stolen', 'latitude',
       'longitude', 'num_guns_involved', 'state_house_district',
       'state_senate_district', 'suicide', 'accidental', 'domestic_violence',
       'gang_related', 'non_shooting_incident', 'gun_shop_robbery',
       'drive_by_shooting', 'officer_involved_shooting', 'child_involved',
       'mass_shooting', 'drug_involved', 'assault_weapon', 'num_participants',
       'avg_participant_age', 'participant_age_ratio', 'num_unharmed',
       'num_arrested', 'num_victims', 'avg_victim_age', 'victim_age_ratio',
       'num_suspects', 'avg_suspect_age', 'suspect_age_ratio'],
      dtype='object')

In [30]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 239679 entries, 0 to 239678
Data columns (total 36 columns):
incident_id                  239679 non-null int64
date                         239679 non-null datetime64[ns]
state                        239679 non-null object
city_or_county               239679 non-null object
num_killed                   239679 non-null int64
num_injured                  239679 non-null int64
congressional_district       227734 non-null float64
gun_stolen                   239679 non-null int64
latitude                     231756 non-null float64
longitude                    231756 non-null float64
num_guns_involved            140228 non-null float64
state_house_district         200906 non-null float64
state_senate_district        207343 non-null float64
suicide                      239679 non-null int64
accidental                   239679 non-null int64
domestic_violence            239679 non-null int64
gang_related                 239679 non-null int64
non_shooting_incident        239679 non-null int64
gun_shop_robbery             239679 non-null int64
drive_by_shooting            239679 non-null int64
officer_involved_shooting    239679 non-null int64
child_involved               239679 non-null int64
mass_shooting                239679 non-null int64
drug_involved                239679 non-null int64
assault_weapon               239679 non-null int64
num_participants             214816 non-null float64
avg_participant_age          147381 non-null float64
participant_age_ratio        147381 non-null float64
num_unharmed                 214816 non-null float64
num_arrested                 214816 non-null float64
num_victims                  155265 non-null float64
avg_victim_age               91585 non-null float64
victim_age_ratio             91585 non-null float64
num_suspects                 239679 non-null int64
avg_suspect_age              87251 non-null float64
suspect_age_ratio            87251 non-null float64
dtypes: datetime64[ns](1), float64(16), int64(17), object(2)
memory usage: 65.8+ MB

In [31]:
aggregations = {
    'incident_id': 'count',
    'num_killed': 'sum',
    'num_injured': 'sum',
    'congressional_district': 'mean',
    'gun_stolen': 'sum',
    'num_guns_involved': 'sum',
    'state_house_district': 'mean',
    'state_senate_district': 'mean',
    'suicide': 'sum',
    'accidental': 'sum',
    'domestic_violence': 'sum',
    'gang_related': 'sum',
    'non_shooting_incident': 'sum',
    'gun_shop_robbery': 'sum',
    'drive_by_shooting': 'sum',
    'officer_involved_shooting': 'sum',
    'child_involved': 'sum',
    'mass_shooting': 'sum',
    'drug_involved': 'sum',
    'assault_weapon': 'sum',
    'num_unharmed': 'sum',
    'num_arrested': 'sum',
    'num_suspects': 'sum',
    'num_victims': 'sum',
    'avg_victim_age': 'mean',
    'victim_age_ratio': 'mean',
    'avg_suspect_age': 'mean',
    'suspect_age_ratio': 'mean',
    'num_participants': 'sum',
    'avg_participant_age': 'mean',
    'participant_age_ratio': 'mean',
    }

df_states = df.groupby(['state', 'date']).agg(aggregations).reset_index()
df_states.rename({'incident_id': 'num_incidents'}, axis = 1, inplace = True)
df_date = df.groupby(['date']).agg(aggregations).reset_index()
df_date.rename({'incident_id': 'num_incidents'}, axis = 1, inplace = True)

In [32]:
df_states.to_pickle('../Pickles/df_states.pkl')
df_date.to_pickle('../Pickles/df_date.pkl')

In [33]:
df_states.head()

,state,date,num_incidents,num_killed,num_injured,congressional_district,gun_stolen,num_guns_involved,state_house_district,state_senate_district,suicide,accidental,domestic_violence,gang_related,non_shooting_incident,gun_shop_robbery,drive_by_shooting,officer_involved_shooting,child_involved,mass_shooting,drug_involved,assault_weapon,num_unharmed,num_arrested,num_suspects,num_victims,avg_victim_age,victim_age_ratio,avg_suspect_age,suspect_age_ratio,num_participants,avg_participant_age,participant_age_ratio
0,Alabama,2013-07-06,1,0,4,5.00,0,0.00,1.00,6.00,0,0,0,0,0,0,0,0,0,1,0,0,1.00,1.00,1,4.00,nan,nan,22.00,0.05,5.00,22.00,0.23
1,Alabama,2013-12-28,1,3,5,2.00,0,0.00,77.00,26.00,1,1,0,0,0,0,0,0,0,1,0,0,2.00,2.00,2,8.00,21.43,0.37,25.00,0.08,10.00,22.22,0.45
2,Alabama,2014-01-01,8,3,6,4.62,0,1.00,41.50,10.75,3,4,0,0,0,0,0,0,0,0,0,0,12.00,0.00,11,11.00,33.00,0.05,20.50,0.10,22.00,30.92,0.14
3,Alabama,2014-01-02,4,2,1,3.75,0,0.00,46.00,15.75,2,2,0,0,0,0,1,0,0,0,2,0,3.00,0.00,3,3.00,29.00,0.04,29.33,0.04,6.00,31.50,0.06
4,Alabama,2014-01-04,6,1,1,5.67,0,0.00,31.67,10.17,0,2,0,0,1,0,0,0,0,0,0,0,10.00,0.00,6,6.00,26.00,0.04,18.00,0.06,12.00,22.00,0.07

In [34]:
df_date.head()

,date,num_incidents,num_killed,num_injured,congressional_district,gun_stolen,num_guns_involved,state_house_district,state_senate_district,suicide,accidental,domestic_violence,gang_related,non_shooting_incident,gun_shop_robbery,drive_by_shooting,officer_involved_shooting,child_involved,mass_shooting,drug_involved,assault_weapon,num_unharmed,num_arrested,num_suspects,num_victims,avg_victim_age,victim_age_ratio,avg_suspect_age,suspect_age_ratio,num_participants,avg_participant_age,participant_age_ratio
0,2013-01-01,3,2,10,22.00,0,2.00,59.00,24.00,2,2,0,1,0,0,0,0,0,2,0,0,2.00,3.00,4,11.00,24.44,0.16,28.00,0.07,15.00,23.73,0.22
1,2013-01-05,1,4,0,6.00,0,0.00,40.00,28.00,1,1,0,0,0,0,0,1,0,0,1,0,0.00,0.00,1,3.00,39.33,0.08,33.00,0.03,4.00,37.75,0.11
2,2013-01-07,2,6,2,3.50,0,2.00,67.00,19.00,2,2,1,0,0,0,0,0,0,1,0,0,2.00,2.00,3,7.00,29.75,0.12,47.00,0.02,10.00,32.38,0.15
3,2013-01-19,1,5,0,1.00,0,2.00,10.00,14.00,1,1,1,0,0,0,0,0,0,1,0,0,1.00,1.00,1,5.00,21.40,0.23,15.00,0.07,6.00,20.33,0.30
4,2013-01-21,2,0,9,5.50,0,0.00,52.00,6.00,0,0,0,1,0,0,2,0,0,2,0,0,1.00,0.00,2,9.00,nan,nan,nan,nan,11.00,nan,nan

In [35]:
# df_states.sort_values(by = ['state', 'date'], ascending = True)

In [36]:
# df_states[df_states['num_killed']==df_states['num_killed'].max()]

In [37]:
# df_states[df_states['gang_related'] == df_states['gang_related'].max()]